name: Email Report

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send email
        run: |
          # Replace the placeholders with your email configuration
          export SMTP_SERVER=your_smtp_server
          export SMTP_PORT=your_smtp_port
          export SMTP_USERNAME=your_smtp_username
          export SMTP_PASSWORD=your_smtp_password
          export EMAIL_FROM=your_email_from
          export EMAIL_TO=your_email_to

          # Replace `report.txt` with the path to your report file
          python send_email.py report.txt